### ISSUE TITLE
scrapy

### ISSUE THREAD

**Issue by lulinha** [lulinha/test#2]
2016-07-20 09:26:47 [RandomProxy] WARNING: Removing http://60.1.145.45:9999 from the proxy pool. 3953 proxies left.
2016-07-20 09:26:54 [RandomProxy] WARNING: Removing http://106.59.201.80:81 from the proxy pool. 3952 proxies left.
2016-07-20 09:26:59 [RandomProxy] WARNING: Removing http://89.203.187.3:8080 from the proxy pool. 3951 proxies left.
2016-07-20 09:27:05 [RandomProxy] WARNING: Removing http://124.113.21.219:8118 from the proxy pool. 3950 proxies left.
2016-07-20 09:27:06 [RandomProxy] WARNING: Removing http://111.248.199.172:81 from the proxy pool. 3949 proxies left.
2016-07-20 09:28:02 [RandomProxy] WARNING: Removing http://120.83.251.205:9999 from the proxy pool. 3948 proxies left.
2016-07-20 09:28:27 [RandomProxy] WARNING: Removing http://101.81.106.12:9000 from the proxy pool. 3947 proxies left.
2016-07-20 09:28:34 [RandomProxy] WARNING: Removing http://112.92.218.252:9999 from the proxy pool. 3946 proxies left.
2016-07-20 09:28:35 [RandomProxy] WARNING: Removing http://104.236.8.75:3128 from the proxy pool. 3945 proxies left.
2016-07-20 09:28:37 [RandomProxy] WARNING: Removing http://121.22.58.210:3128 from the proxy pool. 3944 proxies left.
2016-07-20 09:28:42 [RandomProxy] WARNING: Removing http://123.234.143.79:81 from the proxy pool. 3943 proxies left.
2016-07-20 09:28:43 [RandomProxy] WARNING: Removing http://43.245.234.11:8080 from the proxy pool. 3942 proxies left.
2016-07-20 09:28:50 [RandomProxy] WARNING: Removing http://120.85.249.153:81 from the proxy pool. 3941 proxies left.
2016-07-20 09:29:01 [RandomProxy] WARNING: Removing http://180.126.80.46:8888 from the proxy pool. 3940 proxies left.
2016-07-20 09:29:05 [RandomProxy] WARNING: Removing http://115.152.152.138:81 from the proxy pool. 3939 proxies left.
2016-07-20 09:29:13 [RandomProxy] WARNING: Removing http://106.59.201.80:81 from the proxy pool. 3938 proxies left.
2016-07-20 09:29:17 [RandomProxy] WARNING: Removing http://60.1.145.45:9999 from the proxy pool. 3938 proxies left.
2016-07-20 09:29:20 [RandomProxy] WARNING: Removing http://104.236.8.75:3128 from the proxy pool. 3938 proxies left.
2016-07-20 09:29:21 [RandomProxy] WARNING: Removing http://49.68.5.143:8888 from the proxy pool. 3938 proxies left.
2016-07-20 09:29:25 [RandomProxy] WARNING: Removing http://1.202.120.130:8888 from the proxy pool. 3937 proxies left.
2016-07-20 09:29:28 [RandomProxy] WARNING: Removing http://123.139.59.242:9999 from the proxy pool. 3936 proxies left.
2016-07-20 09:29:31 [RandomProxy] WARNING: Removing http://89.203.187.3:8080 from the proxy pool. 3935 proxies left.
2016-07-20 09:29:39 [RandomProxy] WARNING: Removing http://111.248.199.172:81 from the proxy pool. 3935 proxies left.
2016-07-20 09:29:43 [RandomProxy] WARNING: Removing http://115.152.152.138:81 from the proxy pool. 3935 proxies left.
2016-07-20 09:30:38 [RandomProxy] WARNING: Removing http://49.117.28.152:8998 from the proxy pool. 3935 proxies left.
2016-07-20 09:30:38 [RandomProxy] WARNING: Removing http://180.126.80.46:8888 from the proxy pool. 3934 proxies left.
2016-07-20 09:30:45 [RandomProxy] WARNING: Removing http://195.138.78.143:3128 from the proxy pool. 3934 proxies left.
2016-07-20 09:30:46 [RandomProxy] WARNING: Removing http://163.125.70.216:9999 from the proxy pool. 3933 proxies left.
2016-07-20 09:30:56 [RandomProxy] WARNING: Removing http://116.226.73.176:63000 from the proxy pool. 3932 proxies left.
2016-07-20 09:30:57 [RandomProxy] WARNING: Removing http://43.245.234.11:8080 from the proxy pool. 3931 proxies left.
2016-07-20 09:31:16 [RandomProxy] WARNING: Removing http://219.157.151.74:8888 from the proxy pool. 3931 proxies left.
2016-07-20 09:31:30 [RandomProxy] WARNING: Removing http://120.85.249.153:81 from the proxy pool. 3930 proxies left.
2016-07-20 09:31:30 [RandomProxy] WARNING: Removing http://190.207.127.47:8080 from the proxy pool. 3930 proxies left.
2016-07-20 09:31:34 [RandomProxy] WARNING: Removing http://123.234.143.79:81 from the proxy pool. 3929 proxies left.
2016-07-20 09:31:54 [RandomProxy] WARNING: Removing http://121.22.58.210:3128 from the proxy pool. 3929 proxies left.
2016-07-20 09:32:49 [RandomProxy] WARNING: Removing http://49.68.5.143:8888 from the proxy pool. 3929 proxies left.
2016-07-20 09:32:52 [RandomProxy] WARNING: Removing http://195.138.78.143:3128 from the proxy pool. 3929 proxies left.
2016-07-20 09:32:53 [RandomProxy] WARNING: Removing http://1.202.120.130:8888 from the proxy pool. 3929 proxies left.
2016-07-20 09:33:08 [RandomProxy] WARNING: Removing http://112.92.218.252:9999 from the proxy pool. 3929 proxies left.
2016-07-20 09:33:19 [RandomProxy] WARNING: Removing http://183.18.167.64:3128 from the proxy pool. 3929 proxies left.
2016-07-20 09:33:26 [RandomProxy] WARNING: Removing http://49.117.28.152:8998 from the proxy pool. 3928 proxies left.
2016-07-20 09:33:28 [RandomProxy] WARNING: Removing http://125.39.118.163:18000 from the proxy pool. 3928 proxies left.
2016-07-20 09:33:41 [RandomProxy] WARNING: Removing http://163.125.70.216:9999 from the proxy pool. 3927 proxies left.
2016-07-20 09:33:41 [RandomProxy] WARNING: Removing http://222.95.34.153:81 from the proxy pool. 3927 proxies left.
2016-07-20 09:33:43 [RandomProxy] WARNING: Removing http://223.95.105.206:80 from the proxy pool. 3926 proxies left.
2016-07-20 09:33:45 [RandomProxy] WARNING: Removing http://116.226.73.176:63000 from the proxy pool. 3925 proxies left.
2016-07-20 09:33:51 [RandomProxy] WARNING: Removing http://36.101.82.107:8888 from the proxy pool. 3925 proxies left.
2016-07-20 09:34:02 [RandomProxy] WARNING: Removing http://5.63.66.202:3128 from the proxy pool. 3924 proxies left.
2016-07-20 09:34:15 [RandomProxy] WARNING: Removing http://118.172.59.206:8080 from the proxy pool. 3923 proxies left.
2016-07-20 09:34:39 [RandomProxy] WARNING: Removing http://219.157.151.74:8888 from the proxy pool. 3922 proxies left.
2016-07-20 09:34:41 [scrapy] ERROR: Spider error processing <GET http://ask.qyer.com/question/983932.html> (referer: http://ask.qyer.com/question/983681.html)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/scrapy/tripSpider/tripSpider/spiders/qyer.py", line 79, in parse_question
    reply_cnt = sel.xpath("//div[@class='ask_detail_comment mt20']//span[@class='fr']/text()").extract()[0]
IndexError: list index out of range
2016-07-20 09:35:17 [RandomProxy] WARNING: Removing http://114.40.111.239:8088 from the proxy pool. 3922 proxies left.
2016-07-20 09:35:39 [RandomProxy] WARNING: Removing http://183.28.38.97:8118 from the proxy pool. 3921 proxies left.
2016-07-20 09:35:40 [RandomProxy] WARNING: Removing http://43.245.234.242:80 from the proxy pool. 3920 proxies left.
2016-07-20 09:36:03 [RandomProxy] WARNING: Removing http://1.164.142.93:8080 from the proxy pool. 3919 proxies left.
2016-07-20 09:36:03 [RandomProxy] WARNING: Removing http://119.98.213.16:8118 from the proxy pool. 3918 proxies left.
2016-07-20 09:36:06 [RandomProxy] WARNING: Removing http://60.189.65.112:9529 from the proxy pool. 3917 proxies left.
2016-07-20 09:36:15 [RandomProxy] WARNING: Removing http://186.94.63.240:8080 from the proxy pool. 3916 proxies left.

**Comment by lulinha** [comment]
# -*- coding: utf-8 -*-

import redis

redis = redis.StrictRedis('localhost')

f = open('scrapy.log', 'r')

with open('scrapy.log', 'r') as f:
    log = f.read()


proxies_list = re.findall('http://\d+\.\d+\.\d+\.\d+:\d+', log)

proxies = set(proxies_list)

# add proxies 
# redis.sadd("scrapy:proxy", *proxies)

# remove proxies
redis.srem("scrapy:proxy", *proxies)

**Comment by lulinha** [comment]
# -*- coding: utf-8 -*-
# Importing base64 library because we'll need it ONLY in case if the proxy we are going to use requires authentication
import random
import base64
import logging
import threading
import redis



class RandomRedisProxy(object):
    def __init__(self, settings):

        self.redis = redis.StrictRedis(host='localhost', port=6379, db=0) 

        self.proxy_pool = set([])
        self.disabled_proxies = set([])

        self._lock = threading.Lock()
        self.logger = logging.getLogger('RandomProxy')

        self.refresh_interval = settings.getint('DYNO_PROXY_REFRESH_INTERVAL', 1800)

        self.schedule_proxies_refresh()


    def update_proxy_pool(self, new_proxies):
        """
        Update the existing proxy pool
        """
        try:
            self._lock.acquire()
            self.proxy_pool = new_proxies - self.disabled_proxies

        finally:
            self._lock.release()

        self.logger.info('Proxy pool has been updated. There are %d proxies in all' % len(self.proxy_pool)) 


    def pick_proxy(self):
        """
        从代理池中随机选择一个代理
        :return:
        """
        proxy_list = random.choice(list(self.proxy_pool))
        if not proxy_list:
            return None
        return proxy_list


    def schedule_proxies_refresh(self):
        """
        Schedule a periodically invoked proxy-fetching task
        """
        self.refresh_proxy_pool()

        interval = self.refresh_interval
        stopped = threading.Event()

        def loop():  # executed in another thread
            while not stopped.wait(interval):  # until stopped
                self.refresh_proxy_pool()

        t = threading.Thread(target=loop)
        t.daemon = True  # stop if the program exits
        t.start()


    def deregister_proxy(self, proxy, spider):
        """
        将某个proxy移除出proxy pool
        """
        self.logger.warning('Removing %s from the proxy pool. %d proxies left.' % (proxy, len(self.proxy_pool)))
        self.disabled_proxies.add(proxy)
        try:
            # self._lock.acquire()
            self.proxy_pool.remove(proxy)
        except KeyError:
            pass
        finally:
            # self._lock.release()
            pass    

    
    def _fetch_proxies(self):
        """
        Fetch proxies from the database
        :param validation_src: the source of the validation, e.g. baidu, google...
        :param max_latency: the maximal latency. Proxies with higher latencies will be filtered out
        :return:
        """
        
        for proxy in self.disabled_proxies:
            self.redis.srem('scrapy:proxy', proxy)

        fetched_proxies = self.redis.smembers('scrapy:proxy') 
        return fetched_proxies

    def refresh_proxy_pool(self):
        fetched_proxies = self._fetch_proxies()
        self.update_proxy_pool(fetched_proxies)           

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.settings)

    def process_request(self, request, spider):
        # Don't overwrite with a random one (server-side state for IP)
        if 'proxy' in request.meta:
            return

        proxy_address = None
        try:
            proxy_address = self.pick_proxy()
            self.logger.debug('Randomly selecting a proxy: %s' % proxy_address)
        except IndexError:
            self.logger.warning('The middleware is bypassed because the proxy pool is empty')

        if proxy_address:
            request.meta['proxy'] = proxy_address

    def process_exception(self, request, exception, spider):
        proxy = request.meta['proxy']
        self.logger.info('Removing failed proxy <%s>, %d proxies left' % (proxy, len(self.proxy_pool)))
        self.deregister_proxy(proxy, spider)

**Comment by lulinha** [comment]
# -*- coding: utf-8 -*-
# Importing base64 library because we'll need it ONLY in case if the proxy we are going to use requires authentication
import random
import base64
import logging
import threading
import redis



class RandomRedisProxy(object):
    def __init__(self, settings):

        self.redis = redis.StrictRedis(host='localhost', port=6379, db=0) 
        
        self.redis_key = "scrapy:proxy"

        self.proxy_pool = set()
        self.disabled_proxies = set()

        self._lock = threading.Lock()
        self.logger = logging.getLogger('RandomProxy')

        self.refresh_interval = settings.getint('DYNO_PROXY_REFRESH_INTERVAL', 1800)

        self.schedule_proxies_refresh()


    def update_proxy_pool(self, new_proxies):
        """
        Update the existing proxy pool
        """
        try:
            self._lock.acquire()
            self.proxy_pool = new_proxies

        finally:
            self._lock.release()

        self.logger.info('Proxy pool has been updated. There are %d proxies in all' % len(self.proxy_pool)) 


    def pick_proxy(self):
        """
        从代理池中随机选择一个代理
        :return:
        """
        proxy_list = random.choice(list(self.proxy_pool))
        if not proxy_list:
            return None
        return proxy_list


    def schedule_proxies_refresh(self):
        """
        Schedule a periodically invoked proxy-fetching task
        """
        self.refresh_proxy_pool()

        interval = self.refresh_interval
        stopped = threading.Event()

        def loop():  # executed in another thread
            while not stopped.wait(interval):  # until stopped
                self.refresh_proxy_pool()

        t = threading.Thread(target=loop)
        t.daemon = True  # stop if the program exits
        t.start()


    def deregister_proxy(self, proxy, spider):
        """
        将某个proxy移除出proxy pool
        """
        self.logger.warning('Removing %s from the proxy pool. %d proxies left.' % (proxy, len(self.proxy_pool)))
        self.disabled_proxies.add(proxy)
        try:
            # self._lock.acquire()
            self.proxy_pool.remove(proxy)
        except KeyError:
            pass
        finally:
            # self._lock.release()
            pass    

    
    def fetch_proxies(self):
    
        # remove disabled proxies from redis first
        if self.disabled_proxies:
           
            self.redis.srem(self.redis_key, *self.disabled_proxies)

        fetched_proxies = self.redis.smembers(self.redis_key) 
        return fetched_proxies

    def refresh_proxy_pool(self):
        fetched_proxies = self.fetch_proxies()
        self.update_proxy_pool(fetched_proxies)           

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.settings)

    def process_request(self, request, spider):
        # Don't overwrite with a random one (server-side state for IP)
        if 'proxy' in request.meta:
            return

        proxy_address = None
        try:
            proxy_address = self.pick_proxy()
            self.logger.debug('Randomly selecting a proxy: %s' % proxy_address)
        except IndexError:
            self.logger.warning('The middleware is bypassed because the proxy pool is empty')

        if proxy_address:
            request.meta['proxy'] = proxy_address

    def process_exception(self, request, exception, spider):
        proxy = request.meta['proxy']
        self.logger.info('Removing failed proxy <%s>, %d proxies left' % (proxy, len(self.proxy_pool)))
        self.deregister_proxy(proxy, spider)
